//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVentaKX.ServiceReferenceKX {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceKX.WebServicesKXSoap")]
    public interface WebServicesKXSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevolverNombreResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverNombre", ReplyAction="*")]
        PuntoVentaKX.ServiceReferenceKX.DevolverNombreResponse DevolverNombre(PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaKX.ServiceReferenceKX.DevolverNombreResponse> DevolverNombreAsync(PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HoraServidorResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HoraServidor", ReplyAction="*")]
        PuntoVentaKX.ServiceReferenceKX.HoraServidorResponse HoraServidor(PuntoVentaKX.ServiceReferenceKX.HoraServidorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HoraServidor", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaKX.ServiceReferenceKX.HoraServidorResponse> HoraServidorAsync(PuntoVentaKX.ServiceReferenceKX.HoraServidorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarReservaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarReserva", ReplyAction="*")]
        PuntoVentaKX.ServiceReferenceKX.BuscarReservaResponse BuscarReserva(PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaKX.ServiceReferenceKX.BuscarReservaResponse> BuscarReservaAsync(PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverNombre", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequestBody Body;
        
        public DevolverNombreRequest() {
        }
        
        public DevolverNombreRequest(PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevolverNombreRequestBody {
        
        public DevolverNombreRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVentaKX.ServiceReferenceKX.DevolverNombreResponseBody Body;
        
        public DevolverNombreResponse() {
        }
        
        public DevolverNombreResponse(PuntoVentaKX.ServiceReferenceKX.DevolverNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DevolverNombreResult;
        
        public DevolverNombreResponseBody() {
        }
        
        public DevolverNombreResponseBody(string DevolverNombreResult) {
            this.DevolverNombreResult = DevolverNombreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HoraServidorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HoraServidor", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVentaKX.ServiceReferenceKX.HoraServidorRequestBody Body;
        
        public HoraServidorRequest() {
        }
        
        public HoraServidorRequest(PuntoVentaKX.ServiceReferenceKX.HoraServidorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HoraServidorRequestBody {
        
        public HoraServidorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HoraServidorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HoraServidorResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVentaKX.ServiceReferenceKX.HoraServidorResponseBody Body;
        
        public HoraServidorResponse() {
        }
        
        public HoraServidorResponse(PuntoVentaKX.ServiceReferenceKX.HoraServidorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HoraServidorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HoraServidorResult;
        
        public HoraServidorResponseBody() {
        }
        
        public HoraServidorResponseBody(string HoraServidorResult) {
            this.HoraServidorResult = HoraServidorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarReserva", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequestBody Body;
        
        public BuscarReservaRequest() {
        }
        
        public BuscarReservaRequest(PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int folio;
        
        public BuscarReservaRequestBody() {
        }
        
        public BuscarReservaRequestBody(int folio) {
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVentaKX.ServiceReferenceKX.BuscarReservaResponseBody Body;
        
        public BuscarReservaResponse() {
        }
        
        public BuscarReservaResponse(PuntoVentaKX.ServiceReferenceKX.BuscarReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVentaKX.ServiceReferenceKX.ArrayOfString BuscarReservaResult;
        
        public BuscarReservaResponseBody() {
        }
        
        public BuscarReservaResponseBody(PuntoVentaKX.ServiceReferenceKX.ArrayOfString BuscarReservaResult) {
            this.BuscarReservaResult = BuscarReservaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicesKXSoapChannel : PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicesKXSoapClient : System.ServiceModel.ClientBase<PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap>, PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap {
        
        public WebServicesKXSoapClient() {
        }
        
        public WebServicesKXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicesKXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesKXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesKXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaKX.ServiceReferenceKX.DevolverNombreResponse PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap.DevolverNombre(PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequest request) {
            return base.Channel.DevolverNombre(request);
        }
        
        public string DevolverNombre() {
            PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequest inValue = new PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequest();
            inValue.Body = new PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequestBody();
            PuntoVentaKX.ServiceReferenceKX.DevolverNombreResponse retVal = ((PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap)(this)).DevolverNombre(inValue);
            return retVal.Body.DevolverNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaKX.ServiceReferenceKX.DevolverNombreResponse> PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap.DevolverNombreAsync(PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequest request) {
            return base.Channel.DevolverNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaKX.ServiceReferenceKX.DevolverNombreResponse> DevolverNombreAsync() {
            PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequest inValue = new PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequest();
            inValue.Body = new PuntoVentaKX.ServiceReferenceKX.DevolverNombreRequestBody();
            return ((PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap)(this)).DevolverNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaKX.ServiceReferenceKX.HoraServidorResponse PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap.HoraServidor(PuntoVentaKX.ServiceReferenceKX.HoraServidorRequest request) {
            return base.Channel.HoraServidor(request);
        }
        
        public string HoraServidor() {
            PuntoVentaKX.ServiceReferenceKX.HoraServidorRequest inValue = new PuntoVentaKX.ServiceReferenceKX.HoraServidorRequest();
            inValue.Body = new PuntoVentaKX.ServiceReferenceKX.HoraServidorRequestBody();
            PuntoVentaKX.ServiceReferenceKX.HoraServidorResponse retVal = ((PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap)(this)).HoraServidor(inValue);
            return retVal.Body.HoraServidorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaKX.ServiceReferenceKX.HoraServidorResponse> PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap.HoraServidorAsync(PuntoVentaKX.ServiceReferenceKX.HoraServidorRequest request) {
            return base.Channel.HoraServidorAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaKX.ServiceReferenceKX.HoraServidorResponse> HoraServidorAsync() {
            PuntoVentaKX.ServiceReferenceKX.HoraServidorRequest inValue = new PuntoVentaKX.ServiceReferenceKX.HoraServidorRequest();
            inValue.Body = new PuntoVentaKX.ServiceReferenceKX.HoraServidorRequestBody();
            return ((PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap)(this)).HoraServidorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaKX.ServiceReferenceKX.BuscarReservaResponse PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap.BuscarReserva(PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequest request) {
            return base.Channel.BuscarReserva(request);
        }
        
        public PuntoVentaKX.ServiceReferenceKX.ArrayOfString BuscarReserva(int folio) {
            PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequest inValue = new PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequest();
            inValue.Body = new PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequestBody();
            inValue.Body.folio = folio;
            PuntoVentaKX.ServiceReferenceKX.BuscarReservaResponse retVal = ((PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap)(this)).BuscarReserva(inValue);
            return retVal.Body.BuscarReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaKX.ServiceReferenceKX.BuscarReservaResponse> PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap.BuscarReservaAsync(PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequest request) {
            return base.Channel.BuscarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaKX.ServiceReferenceKX.BuscarReservaResponse> BuscarReservaAsync(int folio) {
            PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequest inValue = new PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequest();
            inValue.Body = new PuntoVentaKX.ServiceReferenceKX.BuscarReservaRequestBody();
            inValue.Body.folio = folio;
            return ((PuntoVentaKX.ServiceReferenceKX.WebServicesKXSoap)(this)).BuscarReservaAsync(inValue);
        }
    }
}
